### PR TITLE
Fixing invalid attributes in audit templates

### PR DESCRIPTION
**Pull request by nimaft**
**Overall Review of Changes:**
Fixes invalid attributes included in goss audit template files. Overview of changes:

- `file` attribute does not take `path` attribute, deleted all the `path` attributes and fixed the file path under `file` attribute
- `file` attribute does not take `contents` attribute, deleted all the `contents` attributes and replaced with `contains` attribute
- `mount` attribute does not take `mountpoint` attribute, deleted all the `mountpoint` attributes and fixed the mount path under `mount` attribute

View [goss json schema](https://github.com/goss-org/goss/blob/master/docs/schema.yaml) for more information.

**Issue Fixes:**
Addresses #3 

**Enhancements:**
N/A

**How has this been tested?:**
Tested on my local EC2 instance running AL2023 machine and it properly produces the audit results.

### CODE REVIEW

**Comment by yousufsujeel** [comment]
@nimaft  We have also been testing this against AL2023 ,Getting the same issue u are facing,  tried to clone your fork, and tested against default variables,  does not seem to work.

root@ip-10-216-94-208 AMAZON2023-CIS-Audit]# ./run_audit.sh -v vars/CIS.yml

## Pre-Checks Start

OK Audit binary /usr/local/bin/goss is available
OK /opt/AMAZON2023-CIS-Audit/goss.yml is available

## Pre-checks Successful

#############
Audit Started
#############


Completed file can be found at /opt/audit_ip-10-216-94-208.ap-southeast-2.compute.internal-CIS-AMAZON2023_1711072323.json
###############
Audit Completed
###############
[root@ip-10-216-94-208 AMAZON2023-CIS-Audit]# cat /opt/audit_ip-10-216-94-208.ap-southeast-2.compute.internal-CIS-AMAZON2023_1711072323.json
Error: failed while loading vars file "vars/CIS.yml": loading vars file 'vars/CIS.yml'
unable to determine format from content
[root@ip-10-216-94-208 AMAZON2023-CIS-Audit]#

There are duplicate variables in default vars,  if we remove them gives modprobe error.
[root@ip-10-216-91-12 AMAZON2023-CIS-Audit]# ./run_audit.sh -v vars/CIS.yml -f junit

## Pre-Checks Start

OK Audit binary /usr/local/bin/goss is available
OK /root/AMAZON2023-CIS-Audit/goss.yml is available

## Pre-checks Successful

#############
Audit Started
#############

2024-03-22T01:35:11Z [DEBUG] Setting log level to DEBUG
2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'file: /etc/modprobe.d/blacklist.conf'. The value from a later-loaded goss file has overwritten the previous value.
2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'file: /etc/modprobe.d/blacklist.conf'. The value from a later-loaded goss file has overwritten the previous value.
2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'command: cramfs'. The value from a later-loaded goss file has overwritten the previous value.
2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'file: /etc/modprobe.d/blacklist.conf'. The value from a later-loaded goss file has overwritten the previous value.
2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'file: /etc/modprobe.d/blacklist.conf'. The value from a later-loaded goss file has overwritten the previous value.
2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'file: /etc/modprobe.d/blacklist.conf'. The value from a later-loaded goss file has overwritten the previous value.
2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'file: /etc/modprobe.d/blacklist.conf'. The value from a later-loaded goss file has overwritten the previous value.

Completed file can be found at /root/audit_ip-10-216-91-12.ap-southeast-2.compute.internal-CIS-AMAZON2023_1711071311.junit
###############
Audit Completed
###############
[root@ip-10-216-91-12 AMAZON2023-CIS-Audit]

**Comment by nimaft** [comment]
> @nimaft We have also been testing this against AL2023 ,Getting the same issue u are facing, tried to clone your fork, and tested against default variables, does not seem to work.
> 
> root@ip-10-216-94-208 AMAZON2023-CIS-Audit]# ./run_audit.sh -v vars/CIS.yml
> 
> ## Pre-Checks Start
> OK Audit binary /usr/local/bin/goss is available OK /opt/AMAZON2023-CIS-Audit/goss.yml is available
> 
> ## Pre-checks Successful
> ############# Audit Started #############
> 
> Completed file can be found at /opt/audit_ip-10-216-94-208.ap-southeast-2.compute.internal-CIS-AMAZON2023_1711072323.json ############### Audit Completed ############### [root@ip-10-216-94-208 AMAZON2023-CIS-Audit]# cat /opt/audit_ip-10-216-94-208.ap-southeast-2.compute.internal-CIS-AMAZON2023_1711072323.json Error: failed while loading vars file "vars/CIS.yml": loading vars file 'vars/CIS.yml' unable to determine format from content [root@ip-10-216-94-208 AMAZON2023-CIS-Audit]#
> 
> There are duplicate variables in default vars, if we remove them gives modprobe error. [root@ip-10-216-91-12 AMAZON2023-CIS-Audit]# ./run_audit.sh -v vars/CIS.yml -f junit
> 
> ## Pre-Checks Start
> OK Audit binary /usr/local/bin/goss is available OK /root/AMAZON2023-CIS-Audit/goss.yml is available
> 
> ## Pre-checks Successful
> ############# Audit Started #############
> 
> 2024-03-22T01:35:11Z [DEBUG] Setting log level to DEBUG 2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'file: /etc/modprobe.d/blacklist.conf'. The value from a later-loaded goss file has overwritten the previous value. 2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'file: /etc/modprobe.d/blacklist.conf'. The value from a later-loaded goss file has overwritten the previous value. 2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'command: cramfs'. The value from a later-loaded goss file has overwritten the previous value. 2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'file: /etc/modprobe.d/blacklist.conf'. The value from a later-loaded goss file has overwritten the previous value. 2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'file: /etc/modprobe.d/blacklist.conf'. The value from a later-loaded goss file has overwritten the previous value. 2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'file: /etc/modprobe.d/blacklist.conf'. The value from a later-loaded goss file has overwritten the previous value. 2024-03-22T01:35:11Z [WARN] Duplicate key detected: 'file: /etc/modprobe.d/blacklist.conf'. The value from a later-loaded goss file has overwritten the previous value.
> 
> Completed file can be found at /root/audit_ip-10-216-91-12.ap-southeast-2.compute.internal-CIS-AMAZON2023_1711071311.junit ############### Audit Completed ############### [root@ip-10-216-91-12 AMAZON2023-CIS-Audit]

Sorry my friend, not sure what causes your problem, but looking at `/root/audit_ip-10-216-91-12.ap-southeast-2.compute.internal-CIS-AMAZON2023_1711071311.junit` would help. Also are you running it from `nimaft/attributeFix` branch?

**Comment by yousufsujeel** [comment]
@nimaft  Yes works now from nimaft/attributeFix,  We noticed that changes made by u work only with goss version 0.3.16, Also the name of the repo should be AMAZON2023-CIS-AUDIT ,  Are u using goss 0.3.16.
Major changes in goss
https://github.com/goss-org/goss/releases/tag/v0.4.0-rc.2

**Comment by nimaft** [comment]
@yousufsujeel glad that it works, now I have an actual person who tested it and confirms the functionality.
Regarding to goss, I install the latest version using `curl -fsSL https://goss.rocks/install | sh`
And yes you need to change the repo name. I change it when I clone it, it should be ` AMAZON2023-CIS-Audit`

**Comment by zadowsmash** [comment]
Hi @nimaft 

If you look at that install script, it is actually pinned to version v0.3.23

image

The changes you have made ultimately make the audit work with goss versions below v0.4.0 before some breaking changes were introduced. See: https://github.com/goss-org/goss/releases/tag/v0.4.0

I have taken a different approach to fix the issues and make it work with the latest version of goss (v0.4.4).

We are still testing it properly but you can take a look here if you are interested:

https://github.com/ansible-lockdown/AMAZON2023-CIS-AUDIT/compare/main...zadowsmash:AMAZON2023-CIS-AUDIT:fix_audit_issues

Once I am happy with the test results I will open a PR 👍

**Comment by nimaft** [comment]
@zadowsmash great point my friend, I overlooked it. Awesome work, and looking forward to it. Please update us.

**Comment by uk-bolly** [comment]
hi @nimaft and @zadowsmash 

Thank you so much for highlighting this.
We have managed to get out of sync on the remediate and the audit portion (this repo) of the benchmark. There are a couple of updates that need to be made to the run_audit script.
I will look to get that added over the next couple of days into devel. to bring it into alignment.

Apologies

uk-bolly

**Comment by nimaft** [comment]
Awesome, thank you @uk-bolly 👏🙏

**Comment by uk-bolly** [comment]
hi @nimaft and @zadowsmash

I would suggest that you use the benchmark branch in most occasions anyway. This is aligned to the benchmark version you are expecting and the devel could be newer.
I will be sorting this out later to day and aligning devel to the benchmark branch as it is out of sync. This will resolve the current issues you are seeing.

Many thanks and apologies for the issues

uk-bolly

**Comment by uk-bolly** [comment]
> hi @nimaft and @zadowsmash
> 
> I would suggest that you use the benchmark branch in most occasions anyway. This is aligned to the benchmark version you are expecting and the devel could be newer. I will be sorting this out later to day and aligning devel to the benchmark branch as it is out of sync. This will resolve the current issues you are seeing.
> 
> Many thanks and apologies for the issues
> 
> uk-bolly

This should all be sorted now, please let us know if there are any issues.

thanks

uk-bolly

**Comment by nimaft** [comment]
Thank you @uk-bolly for the information, and thanks for fixing the issue.

**Comment by uk-bolly** [comment]
> Thank you @uk-bolly for the information, and thanks for fixing the issue.

Thank you @nimaft for highlighting the issue and bring it to our attention. I believe if all is working as expected we should be able to close this PR and associated issue?

thanks

uk-bolly

**Pull request closed without merging**
